replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: 11.5

configmap:
  data: {}

peristentVolume:
  enabled: false

service:
  type: ClusterIP
  port: 5432

ingress:
  enabled: false

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}

securityContext: {}

resources: {}

postfix: ""
