# Default values for duo-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: ghcr.io/userofficeproject/user-office-backend
  tag: develop
  pullPolicy: Always

env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: duo-db-svcbind-custom-user
        key: uri

envFrom: {}

secret:
  data:
    secret: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 4000

ingress:
  enabled: true
  pathType: ImplementationSpecific
  paths:
    - /download
    - /preview
    - /downloads
    - /uploads
    - /files
    - /graphql
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.org/client-max-body-size: "16m"

resources: {}

# -- Backend component needs a storage for Uploads.
persistence:
  # -- If false, an EmptyDir is used.
  enabled: false
  size: ""
  storageClassName: ""
  # Should be ReadWriteMany, unless only one Pod is deployed.
  accessMode: ReadWriteMany

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbePath: /health

readinessProbePath: /readiness

postfix: ""
