# Default values for duo-factory.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/userofficeproject/user-office-factory
  tag: develop
  pullPolicy: Always

env:
  - name: DATABASE_HOSTNAME
    valueFrom:
      secretKeyRef:
        name: duo-db-secret
        key: POSTGRES_HOSTNAME
  - name: DATABASE_PORT
    valueFrom:
      secretKeyRef:
        name: duo-db-secret
        key: POSTGRES_PORT
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: duo-db-secret
        key: POSTGRES_USER
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: duo-db-secret
        key: POSTGRES_PASSWORD
  - name: DATABASE_DATABASE
    valueFrom:
      secretKeyRef:
        name: duo-db-secret
        key: POSTGRES_DB

envFrom: {}

configmap:
  data:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    add:
      - SYS_ADMIN

service:
  type: ClusterIP
  port: 4500

resources:
  requests:
    ephemeral-storage: "128Mi"
  limits:
    ephemeral-storage: "256Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbePath: /health-check

readinessProbePath: /health-check

postfix: ""
