# Default values for duo-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

maxSurge: 1

image:
  repository: ghcr.io/userofficeproject/user-office-frontend
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  pathType: ImplementationSpecific
  paths:
    - /
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.org/client-max-body-size: "16m"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

postfix: ""
