duo-backend:
  configmap:
    data:
      AUTH_CLIENT_ID: # Client ID for OIDC
      AUTH_CLIENT_SECRET: # Secret for OIDC
      AUTH_DISCOVERY_URL: # Well-known URL for OIDC
      BASE_URL: localhost:4000
      DATE_FORMAT: dd-MM-yyyy
      DATE_TIME_FORMAT: dd-MM-yyyy HH:mm
      DEPENDENCY_CONFIG: ess
      JWT_SECRET: secret
      JWT_TOKEN_LIFE: 7d
      NODE_ENV: development
      RABBITMQ_CORE_EXCHANGE_NAME: user_office_backend.fanout
      TZ: Europe/Stockholm
      USER_OFFICE_ENDPOINT: http://duo-backend:4000/graphql
      USER_OFFICE_FACTORY_ENDPOINT: http://duo-factory:4500/generate
  env:
    - name: RABBITMQ_HOSTNAME
      valueFrom:
        secretKeyRef:
          key: host
          name: duo-rabbitmq-svcbind
    - name: RABBITMQ_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: duo-rabbitmq-svcbind
    - name: RABBITMQ_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: duo-rabbitmq-svcbind
  ingress:
    enabled: true
    host: localhost
  replicaCount: 1
  secret:
    data:
      SPARKPOST_TOKEN: Y2hhbmdldGhpc3NlY3JldA==

duo-frontend:
  ingress:
    enabled: true
    host: localhost
  replicaCount: 1

duo-gateway:
  ingress:
    hosts:
      - host: scheduler.localhost
        paths:
          - /gateway
  replicaCount: 1

duo-scheduler-backend:
  configmap:
    data:
      RABBITMQ_PROPOSAL_SCHEDULING_QUEUE_NAME: user-office-backend.proposal_scheduling.queue
      RABBITMQ_SCHEDULER_EXCHANGE_NAME: user_office_scheduler_backend.fanout
      UPSERT_PROPOSAL_BOOKING_TRIGGER_STATUSES: SCHEDULING
        USER_OFFICE_SCHEDULER_ENDPOINT: http://duo-scheduler-backend:4000/graphql
  replicaCount: 1
duo-scheduler-frontend:
  ingress:
    enabled: true
    host: scheduler.localhost
  replicaCount: 1

rabbitmq:
  auth:
    password: duo-password
    username: duo-user
    secretName: duo-rabbitmq-svcbind
  enabled: true
  persistence:
    enabled: false

scheduler:
  enabled: true
