duo-frontend:
  replicaCount: 1
  ingress:
    enabled: true
    host: localhost

duo-backend:
  replicaCount: 1
  ingress:
    enabled: true
    host: localhost
  configmap:
    data:
      AUTH_CLIENT_ID: # Client ID for OIDC
      AUTH_CLIENT_SECRET: # Secret for OIDC
      AUTH_DISCOVERY_URL: # Well-known URL for OIDC
      NODE_ENV: development
      TZ: Europe/Stockholm
      BASE_URL: localhost:4000
      JWT_TOKEN_LIFE: 7d
      JWT_SECRET: secret
      DATE_FORMAT: dd-MM-yyyy
      DATE_TIME_FORMAT: dd-MM-yyyy HH:mm
      USER_OFFICE_FACTORY_ENDPOINT: http://user-office-app-duo-factory:4500/generate

rabbitmq:
  enabled: false
  auth:
    username: duo-user
    password: duo-password
  persistence:
    enabled: false

duo-db:
  fullnameOverride: duo-db
  serviceBindings:
    enabled: true
  persistence:
    enabled: false
  auth:
    username: duo-user
    password: duo-password
    database: duo
